
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: api
  password: S7dy89%r
  host: localhost
  post: 3306

development:
  <<: *default
  database: admin_api_development

test:
  <<: *default
  database: admin_api_test

production:
  <<: *default
  database: admin_api_production
